[package]
name = "vulkan-computing-toolkit"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = {version = "0.38.*", default-features = false, features = ["linked"]}
thiserror = {version = "2.*"}
include-bytes-plus = {version = "*"}
serial_test = {version = "3.*"}

[[test]]
name = "shader_tests"
path = "tests/shader_tests.rs"
